// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1IpR9CqS3-sj9obJJ21CZDLnUGnwgJPs',
    appId: '1:54439608927:web:157761ef4401dd395f11ea',
    messagingSenderId: '54439608927',
    projectId: 'taskmanager-1367d',
    authDomain: 'taskmanager-1367d.firebaseapp.com',
    storageBucket: 'taskmanager-1367d.firebasestorage.app',
    measurementId: 'G-4YDZWDE5ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg3YD_vUUL8ghr1sdCVjQqKxhkJsydXwE',
    appId: '1:54439608927:android:def3e175d9c5cedf5f11ea',
    messagingSenderId: '54439608927',
    projectId: 'taskmanager-1367d',
    storageBucket: 'taskmanager-1367d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6t5Cl1tqO38LMCNT1nFTtZ_YJXQ4zwTI',
    appId: '1:54439608927:ios:3e151b22ce88fb7e5f11ea',
    messagingSenderId: '54439608927',
    projectId: 'taskmanager-1367d',
    storageBucket: 'taskmanager-1367d.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6t5Cl1tqO38LMCNT1nFTtZ_YJXQ4zwTI',
    appId: '1:54439608927:ios:3e151b22ce88fb7e5f11ea',
    messagingSenderId: '54439608927',
    projectId: 'taskmanager-1367d',
    storageBucket: 'taskmanager-1367d.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1IpR9CqS3-sj9obJJ21CZDLnUGnwgJPs',
    appId: '1:54439608927:web:d2ef57817adf6c045f11ea',
    messagingSenderId: '54439608927',
    projectId: 'taskmanager-1367d',
    authDomain: 'taskmanager-1367d.firebaseapp.com',
    storageBucket: 'taskmanager-1367d.firebasestorage.app',
    measurementId: 'G-HR66GWXDYP',
  );

}